import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crias LTDA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en" style={{scrollBehavior: 'smooth'}} className="bg-gray-500">
       <link rel="shortcut icon" href="/Logo.png" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}

